paths:
  .github/workflows/release-draft.yml:
    ignore:
      - '^unexpected key "queue" for "concurrency" section\. expected one of "cancel-in-progress", "group"$'
  .github/workflows/publish.yml:
    ignore:
      - '^unexpected key "queue" for "concurrency" section\. expected one of "cancel-in-progress", "group"$'
