import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "toolkit"))

from migration_guides import linked_notes, plan_guides
from migration_notes import REQUIRED_SECTIONS, render
from update_release_draft import combine_notes


class BaselineEquivalenceTests(unittest.TestCase):
    def test_rendered_outputs_match_pr108_except_required_introduction(self):
        # Captured from the actual c178afbb upstream code, not generated by this implementation.
        expected = json.loads((ROOT / "tests" / "fixtures" / "pr108-output.json").read_text(encoding="utf-8"))
        introduction = "Requests now time out instead of waiting indefinitely.\n\n"
        expected["notes"] = expected["notes"].replace(
            "#### Previous behavior", introduction + "#### Previous behavior", 1
        )
        topic_path = "docs/migrations/2.0.0/request-timeout.md"
        expected["documents"][topic_path] = expected["documents"][topic_path].replace(
            "## Previous behavior", introduction + "## Previous behavior", 1
        )
        note = "### Request timeout default\n\n" + introduction + "".join(
            f"#### {section}\n\nMeaningful {section.lower()} guidance.\n\n"
            for section in REQUIRED_SECTIONS
        ) + '```shell\n# Literal heading\necho "$OWNER"\n```\n'
        with tempfile.TemporaryDirectory() as directory:
            repo = Path(directory)

            def git(*args):
                subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)

            git("init", "-q", "-b", "main")
            git("config", "user.name", "Baseline fixture")
            git("config", "user.email", "fixture@example.invalid")
            git("config", "core.autocrlf", "false")
            git("commit", "--allow-empty", "-qm", "Initial")
            git("tag", "v1.0.0")
            (repo / ".changes").mkdir()
            (repo / ".changes" / "+request-timeout.breaking.md").write_text(note, encoding="utf-8", newline="\n")
            git("add", ".")
            git("commit", "-qm", "Breaking change")
            notes = render(repo, "refs/tags/v1.0.0", "HEAD")
            actual = {
                "notes": notes,
                "documents": plan_guides(repo, "HEAD", notes, "v2.0.0", []),
                "body": combine_notes(
                    "<!-- migration-base: v1.0.0 -->\n## What's Changed\n\n### Breaking Changes\n\n"
                    "- Request timeout default (#7) by @example\n",
                    linked_notes(notes, "v2.0.0", "example/library"),
                ),
            }
            self.assertEqual(expected, actual)


if __name__ == "__main__":
    unittest.main()
